settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: api
    path: api
    commands:
      build:
        status: true
        method: go build -o /go/bin/api
      run:
        status: true
        method: /go/bin/api
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
